# OhMyZSH things

export ZSH=/home/anton/.oh-my-zsh

ZSH_THEME="dieter"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(zsh-syntax-highlighting git archlinux common-aliaces lol sudo systemd wd)

source $ZSH/oh-my-zsh.sh
# User configuration

export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R '
export EDITOR='nvim'

export GOPATH=$HOME/gocode

export PATH="$(ruby -e 'print Gem.user_dir')/bin:$GOPATH/bin:/usr/local/sbin:\
/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl\
:/usr/bin/core_perl:/home/anton/.cabal/bin:/scripts"

# Aliaces
alias winmv='convmv -f cp1252 -t cp850 * --notest  && convmv -f cp866 -t utf-8 * --notest'
alias vpn-kaliwe='sudo openvpn ~/.openvpn/kaliwe/client.ovpn'
